In [1]:
import pandas as pd
from sklearn.datasets import load_iris

IRIS = load_iris()
iris= pd.DataFrame(IRIS.data, columns=IRIS.feature_names)

iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

iris['class']  = IRIS.target
iris['class']  = iris['class'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

In [2]:
print(IRIS.target)
print(type(IRIS.target))
iris.columns

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
<class 'numpy.ndarray'>

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='str')

In [3]:
iris.groupby('class').median()

            sepal_length  sepal_width  petal_length  petal_width
class
setosa               5.0          3.4          1.50          0.2
versicolor           5.9          2.8          4.35          1.3
virginica            6.5          3.0          5.55          2.0

In [4]:
print(pd.Series(iris['class']).value_counts())
print(iris['class'].value_counts())
print(type(iris['class']))
print(type(iris['class'].value_counts()))

class
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64
class
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64
<class 'pandas.Series'>
<class 'pandas.Series'>

In [5]:
iris['petal_width_level'] = pd.qcut(iris['petal_width'], q=3, labels=['small', 'medium', 'large'])
iris['petal_width_level'].value_counts().to_frame()

                   count
petal_width_level
medium                52
small                 50
large                 48

In [6]:
pd.crosstab(iris['petal_width_level'], iris['class'])

class              setosa  versicolor  virginica
petal_width_level
small                  50           0          0
medium                  0          48          4
large                   0           2         46

In [7]:
pd.crosstab(iris['petal_width_level'], iris['class'], normalize='all')

class                setosa  versicolor  virginica
petal_width_level
small              0.333333    0.000000   0.000000
medium             0.000000    0.320000   0.026667
large              0.000000    0.013333   0.306667