In [9]:
import pandas as pd

HR1 = pd.DataFrame(
    {"이름": ["장화", "홍련"],
     "부서": ["영업", "회계"],
     "직급": ["팀장", "사원"]})
HR2 = pd.DataFrame(
    {"이름": ["콩쥐", "팥쥐"],
     "직급": ["사원", "팀장"],
     "부서": ["영업", "인사"]
     })

In [10]:
print(HR1)
print(HR2)

   이름  부서  직급
0  장화  영업  팀장
1  홍련  회계  사원
   이름  직급  부서
0  콩쥐  사원  영업
1  팥쥐  팀장  인사

In [11]:
pd.concat([HR1, HR2], axis=0)

   이름  부서  직급
0  장화  영업  팀장
1  홍련  회계  사원
0  콩쥐  영업  사원
1  팥쥐  인사  팀장

In [12]:
pd.concat([HR1, HR2], axis=0, ignore_index=True)

   이름  부서  직급
0  장화  영업  팀장
1  홍련  회계  사원
2  콩쥐  영업  사원
3  팥쥐  인사  팀장

In [13]:
HR3 = pd.DataFrame(
    {"이름": ["콩쥐", "팥쥐"],
     "부서": ["영업", "인사"],
     "급여":[3500, 2800]})

In [14]:
pd.concat([HR1, HR3], axis=0, ignore_index=True)

   이름  부서   직급      급여
0  장화  영업   팀장     NaN
1  홍련  회계   사원     NaN
2  콩쥐  영업  NaN  3500.0
3  팥쥐  인사  NaN  2800.0

In [15]:
HR4 = pd.Series([None, 2500], name="급여")

In [16]:
pd.concat([HR1, HR4], axis=1)

   이름  부서  직급      급여
0  장화  영업  팀장     NaN
1  홍련  회계  사원  2500.0

In [17]:
HR5 = pd.DataFrame(
    {"급여": [4500, 3000, 3500]}
)

In [18]:
pd.concat([HR1, HR5], axis=1)

    이름   부서   직급    급여
0   장화   영업   팀장  4500
1   홍련   회계   사원  3000
2  NaN  NaN  NaN  3500