## 핵심 요약
train_test_split은 잘 나눠준다

In [1]:
# 데이터 로드 부분

import pandas as pd
from sklearn.datasets import load_iris

iris_raw = load_iris()
iris = pd.DataFrame(data=iris_raw.data, columns=iris_raw.feature_names)
iris['class'] = iris_raw.target
iris['class'] = iris['class'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.drop('class', axis=1), iris['class'], test_size=0.2, random_state=1004)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(120, 4) (120,)
(30, 4) (30,)

In [3]:
X_train.head()

     sepal_length  sepal_width  petal_length  petal_width
87            6.3          2.3           4.4          1.3
67            5.8          2.7           4.1          1.0
131           7.9          3.8           6.4          2.0
74            6.4          2.9           4.3          1.3
63            6.1          2.9           4.7          1.4

In [4]:
y_train.head()

87     versicolor
67     versicolor
131     virginica
74     versicolor
63     versicolor
Name: class, dtype: str

In [5]:
iris['class'].value_counts()

class
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [6]:
y_train.value_counts()

class
versicolor    41
setosa        40
virginica     39
Name: count, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(iris.drop('class', axis=1), iris['class'], test_size=0.2, stratify=iris['class'])
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(120, 4) (120,)
(30, 4) (30,)

In [8]:
y_train.value_counts()

class
setosa        40
virginica     40
versicolor    40
Name: count, dtype: int64

In [9]:
from sklearn.preprocessing import StandardScaler

stdScaler = StandardScaler()

# transform() 메서드는 fit() 메서드로 계산된 평균과 표준편차를 사용하여 데이터를 변환합니다.
#X_train_scaled = stdScaler.transform(X_train)
# fit_transform() 메서드는 fit()과 transform()을 한 번에 수행하는 메서드입니다. 즉, 데이터를 표준화하기 위해 평균과 표준편차를 계산하고, 그 계산된 값을 사용하여 데이터를 변환합니다.
# 둘 중 하나를 사용하면 되지만, fit_transform() 메서드를 사용하는 것이 더 간편합니다.
X_train_scaled = stdScaler.fit_transform(X_train)

X_test_scaled = stdScaler.transform(X_test)

In [10]:
print("\t\t(min, max) (mean, std)")
print("Train_scaled (%.2f, %.2f) (%.2f, %.2f)" % (X_train_scaled.min(), X_train_scaled.max(), X_train_scaled.mean(), X_train_scaled.std()))
print("Test_scaled (%.2f, %.2f) (%.2f, %.2f)" % (X_test_scaled.min(), X_test_scaled.max(), X_test_scaled.mean(), X_test_scaled.std()))

		(min, max) (mean, std)
Train_scaled (-2.36, 3.08) (0.00, 1.00)
Test_scaled (-1.93, 2.29) (0.04, 1.05)

In [11]:
from sklearn.preprocessing import MinMaxScaler

minMaxScaler = MinMaxScaler()

X_train_scaled = minMaxScaler.fit_transform(X_train)
X_test_scaled = minMaxScaler.transform(X_test)
print("\t\t(min, max) (mean, std)")
print("Train_scaled (%.2f, %.2f) (%.2f, %.2f)" % (X_train_scaled.min(), X_train_scaled.max(), X_train_scaled.mean(), X_train_scaled.std()))
print("Test_scaled (%.2f, %.2f) (%.2f, %.2f)" % (X_test_scaled.min(), X_test_scaled.max(), X_test_scaled.mean(), X_test_scaled.std()))

		(min, max) (mean, std)
Train_scaled (0.00, 1.00) (0.44, 0.26)
Test_scaled (-0.03, 1.00) (0.45, 0.28)

In [12]:
from sklearn.preprocessing import MaxAbsScaler

maxabsScaler = MaxAbsScaler()

X_train_scaled = maxabsScaler.fit_transform(X_train)
X_test_scaled = maxabsScaler.transform(X_test)
print("\t\t(min, max) (mean, std)")
print("Train_scaled (%.2f, %.2f) (%.2f, %.2f)" % (X_train_scaled.min(), X_train_scaled.max(), X_train_scaled.mean(), X_train_scaled.std()))
print("Test_scaled (%.2f, %.2f) (%.2f, %.2f)" % (X_test_scaled.min(), X_test_scaled.max(), X_test_scaled.mean(), X_test_scaled.std()))

		(min, max) (mean, std)
Train_scaled (0.04, 1.00) (0.61, 0.23)
Test_scaled (0.04, 1.00) (0.62, 0.25)

In [13]:
from sklearn.preprocessing import RobustScaler

robScaler = RobustScaler()

X_train_scaled = robScaler.fit_transform(X_train)
X_test_scaled = robScaler.transform(X_test)
print("\t\t(min, max) (mean, std)")
print("Train_scaled (%.2f, %.2f) (%.2f, %.2f)" % (X_train_scaled.min(), X_train_scaled.max(), X_train_scaled.mean(), X_train_scaled.std()))
print("Test_scaled (%.2f, %.2f) (%.2f, %.2f)" % (X_test_scaled.min(), X_test_scaled.max(), X_test_scaled.mean(), X_test_scaled.std()))

		(min, max) (mean, std)
Train_scaled (-2.00, 2.80) (-0.03, 0.65)
Test_scaled (-1.20, 2.00) (0.00, 0.67)

In [14]:
pd.DataFrame(X_train_scaled, columns=X_train.columns).head()

   sepal_length  sepal_width  petal_length  petal_width
0     -0.692308          1.2     -0.836879    -0.800000
1     -0.307692          1.8     -0.751773    -0.600000
2      0.153846         -1.6      0.184397     0.133333
3      0.461538         -0.4      0.354610     0.600000
4      0.230769         -0.4     -0.099291     0.000000

In [15]:
X_original = robScaler.inverse_transform(X_train_scaled)
pd.DataFrame(X_original, columns=X_train.columns).head()

   sepal_length  sepal_width  petal_length  petal_width
0           4.9          3.6           1.4          0.1
1           5.4          3.9           1.7          0.4
2           6.0          2.2           5.0          1.5
3           6.4          2.8           5.6          2.2
4           6.1          2.8           4.0          1.3

In [16]:
print(type(X_train_scaled), X_train_scaled.shape)

<class 'numpy.ndarray'> (120, 4)